version: "3.8"

services:
    # nginx:
    #     image: nginx:latest
    #     volumes:
    #         - ./nginx.conf:/etc/nginx/nginx.conf
    #     ports:
    #         - "80:80"
    #     depends_on:
    #         - frontend
    #         - backend
    frontend:
        build: ../../part1/1.12
        ports:
            - "5000:5000"
    backend:
        build: ../../part1/1.13
        ports:
            - "8080:8080"
        environment:
            - REDIS_HOST=redis
            - POSTGRES_HOST=db
    redis:
        image: redis
        restart: unless-stopped
    db:
        image: postgres
        restart: unless-stopped
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRESS_DATABASE=postgres
        volumes:
            - ./database:/var/lib/postgresql/data
